#ifndef APP_MEMLOG_H
#define APP_MEMLOG_H

enum MemoryLogLevel {
	LEXICOGRAPHIC_ANALYSER_READ_WORD = 0,
	LEXICOGRAPHIC_ANALYSER_READ_ORDERING = 1,
	LEXICOGRAPHIC_ANALYSER_GET_RESULT = 2
};

enum MemoryLogType {
	ARRANGEMENT_LIST_UPDATE = 0,
	ARRANGEMENT_LIST_CREATE = 1,
	ARRANGEMENT_LIST_FIND = 2,
	ARRANGEMENT_LIST_QUICK_SORT = 3,
	ARRANGEMENT_LIST_SELECTION_SORT = 3
};

#endif
